name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Validate JavaScript syntax
        run: |
          node -c select-list-card.js
          echo "JavaScript syntax validation passed"

      - name: Upload build file to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: select-list-card.js
          asset_name: select-list-card.js
          tag: ${{ github.ref }}
          overwrite: true
